foodie_network/apps/custom_account/urls.py
from django.conf.urls import url
from django.urls import re_path, include
from . import views


urlpatterns = [
    re_path(r'^', include('allauth.urls' )),

]

foodie_network/apps/friendship/urls.py
try:
    from django.conf.urls import url
except ImportError:
    from django.conf.urls.defaults import url
from .views import view_friends, friendship_add_friend, friendship_accept, \
    friendship_reject, friendship_cancel, friendship_request_list, \
    friendship_request_list_rejected, friendship_requests_detail, followers,\
    following, follower_add, follower_remove, all_users, friendship_requests_sent_list, remove_friend

app_name = 'friendship'

urlpatterns = [
    url(
        regex=r'^users/$',
        view=all_users,
        name='friendship_view_users',
    ),
    url(
        regex=r'^friends/(?P<username>[\w-]+)/$',
        view=view_friends,
        name='friendship_view_friends',
    ),
    url(
        regex=r'^friend/add/(?P<to_username>[\w-]+)/$',
        view=friendship_add_friend,
        name='friendship_add_friend',
    ),
    url(
        regex=r'^friend/accept/(?P<friendship_request_id>\d+)/$',
        view=friendship_accept,
        name='friendship_accept',
    ),
    url(
        regex=r'^friend/reject/(?P<friendship_request_id>\d+)/$',
        view=friendship_reject,
        name='friendship_reject',
    ),
    url(
        regex=r'^friend/cancel/(?P<friendship_request_id>\d+)/$',
        view=friendship_cancel,
        name='friendship_cancel',
    ),
    url(
        regex=r'^friend/requests/$',
        view=friendship_request_list,
        name='friendship_request_list',
    ),
    url(
        regex=r'^friend/sent_requests/$',
        view=friendship_requests_sent_list,
        name='friendship_requests_sent_list',
    ),
    url(
        regex=r'^friend/requests/rejected/$',
        view=friendship_request_list_rejected,
        name='friendship_requests_rejected',
    ),
    url(
        regex=r'^friend/request/(?P<friendship_request_id>\d+)/$',
        view=friendship_requests_detail,
        name='friendship_requests_detail',
    ),
    url(
        regex=r'^followers/(?P<username>[\w-]+)/$',
        view=followers,
        name='friendship_followers',
    ),
    url(
        regex=r'^following/(?P<username>[\w-]+)/$',
        view=following,
        name='friendship_following',
    ),
    url(
        regex=r'^follower/add/(?P<followee_username>[\w-]+)/$',
        view=follower_add,
        name='follower_add',
    ),
    url(
        regex=r'^follower/remove/(?P<followee_username>[\w-]+)/$',
        view=follower_remove,
        name='follower_remove',
    ),
    url(
        regex=r'^follower/remove_friend/(?P<friend_username>[\w-]+)/$',
        view=remove_friend,
        name='remove_friend',
    ),
]

foodie_network/apps/userprofiles/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'userprofiles'

urlpatterns = [
url(r'^details/(?P<pk>\d+)/$', views.PublicProfileView.as_view(), name = 'public_profile'),
url(r'^privdetails/(?P<pk>\d+)/$', views.UserProfileView.as_view(), name = 'user_profile'),
url(r'^profileform/(?P<pk>\d+)/$', views.update_profile, name='profile_form'),
]

# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodie_network/foodie_network/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from . import views
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^profiles/', include('apps.userprofiles.urls')),
    url(r'^accounts/', include('apps.custom_account.urls')),
    url(r'^search/', include('apps.search.urls')),
    url(r'^friendship/', include('apps.friendship.urls')),
    url(r'^restaurant/', include('apps.restaurants.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

foodie_network/apps/userprofiles/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings
from django.urls import reverse

User = get_user_model()
#signal handling
from django.db.models.signals import post_save, post_init
from django.dispatch import receiver
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE, related_name='profile')
    date_of_birth = models.DateField(blank=True, null = True)
    #not sure of this null = true
    profile_pic = models.ImageField(upload_to = 'userprofiles/profile_pics',blank = True, null=True )
    display_status = models.TextField(default="Hey there! Welcome to my profile!")

    # def get_absolute_url(self):
    #     return reverse('userprofiles:profile_info', kwargs={'id':self.pk})

    def __str__(self):
        return str(self.user.first_name)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

foodie_network/apps/userprofiles/forms.py
from django import forms
from .models import Profile
from django.contrib.auth import get_user_model
User = get_user_model()
import datetime

now = datetime.datetime.now()

def get_year():
    years = []
    presentyear = now.year - 130
    for i in range(131):
        years.append(presentyear)
        presentyear += 1
    return years

years = get_year()
class ProfileForm(forms.ModelForm):
    date_of_birth = forms.DateField(widget=forms.SelectDateWidget(years = years))
    # display_status = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'profile_pic', 'display_status')

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')

foodie_network/apps/userprofiles/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.contrib import messages
from .forms import ProfileForm, UserForm
from .models import Profile


# Create your views here.
User = get_user_model()


class PublicProfileView(LoginRequiredMixin,DetailView):
    model = User
    context_object_name = 'other_user'
    template_name = 'userprofiles/public_profile.html'

class UserProfileView(LoginRequiredMixin,DetailView):
    model = User
    template_name = 'userprofiles/user_profile.html'

#Function to update profile
@login_required
@transaction.atomic
def update_profile(request,pk):
    if request.method == "POST":
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        user_form = UserForm(request.POST, instance=request.user)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Yay! You updated the details successfully!")
            return redirect('userprofiles:user_profile', pk=pk)
        else:
            messages.error(request,("Please fix the errors!"))
    else:
        user_form = UserForm(instance = request.user)
        profile_form = ProfileForm(instance = request.user.profile)

        return render(request, 'userprofiles/profile_form.html', {'user_form':user_form,
                                                                    'profile_form':profile_form})

foodie_network/apps/userprofiles/templates/userprofiles/profile_form.html
{% extends "base.html" %}

{% block body_block %}
<div class="jumbotron">
  <form  method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{user_form.as_p}}
    {{profile_form.as_p}}
    <input type="submit"  value="submit">
  </form>

</div>

{% endblock %}

foodie_network/apps/userprofiles/templates/userprofiles/public_profile.html
{% extends "base.html" %}
{% load friendshiptags %}

{% block body_block %}
<div class="container" >
  <div class="card" style="style="width: 45rem; margin:auto; height:auto;"">

    <div class="card-body">
      <img  style="width:20%; margin-right:2em;" class="rounded float-left" src="{{other_user.profile.profile_pic.url}}"
         alt="http://watchfit.com/images/empty_profile_300.png?&width=100&imageType=jpg&quality=85">
     <div style="margin:auto;">
       <h5 class="card-title">{{other_user.first_name}} {{other_user.last_name}}</h5>
       <p class="card-text">{{other_user.profile.display_status}}</p>
     </div>

    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">DOB: {{other_user.profile.date_of_birth|date:"D, d /m /Y"}}</li>
      <li class="list-group-item"><a href="{% url 'friendship:friendship_view_friends' other_user.username%}">View Friends</a></li>
    </ul>
    <div class="card-body">
      {% are_they_friends as are_friends %}
      {% if are_friends %}
      <div class="btn-group dropup">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Friends
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="#">Some action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'friendship:remove_friend' other_user.username%}">Unfriend</a>
        </div>
      </div>

      {% else %}
      <a href="{% url 'friendship:friendship_add_friend' other_user.username %}" class="btn btn-primary btn-lg active card-link" role="button" aria-pressed="true" >Add friend</a>
      {% endif %}
      <a href="{% url 'friendship:follower_add' other_user.username %}" class="btn btn-primary card-link" role="button" aria-pressed="true">Follow</a>
    </div>
  </div>
</div>
{% endblock %}

foodie_network/apps/userprofiles/templates/userprofiles/user_profile.html
{% extends "base.html" %}

{% block body_block %}

<div class="container" >
  <div class="card" style="style="width: 45rem; margin:auto; height:auto;"">

    <div class="card-body">
      <img  style="width:20%; margin-right:2em;" class="rounded float-left" src="{{user.profile.profile_pic.url}}" alt="Card image cap">
     <div style="margin:auto;">
       <h5 class="card-title">{{user.first_name}} {{user.last_name}}</h5>
       <p class="card-text">{{user.profile.display_status}}</p>
     </div>

    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">DOB: {{user.profile.date_of_birth|date:"D, d /m /Y"}}</li>
      <li class="list-group-item"><a href="{% url 'friendship:friendship_view_friends' user.username%}">View Friends</a></li>
    </ul>
    <div class="card-body">
      <a href="{% url 'userprofiles:profile_form' pk=user.pk %}" class="card-link btn btn-primary" role="button">Edit profile</a>

    </div>
  </div>
</div>



{% endblock %}



<div class="container">
  <div class="jumbotron">
    <h2>Name: {{user.first_name}} {{user.last_name}}</h2>
    {% if  user.profile.date_of_birth%}<h2>DOB: {{user.profile.date_of_birth|date:"D, d /m /Y"}}</h2>{% endif %}
    {% if user.profile.profile_pic %}<img src="{{user.profile.profile_pic.url}}">{% endif %}
    <h3><a href="{% url 'userprofiles:profile_form' pk=user.pk %}">Edit Profile</a></h3>


    <br>
  </div>
  </div>