foodie_network/apps/custom_account/urls.py
from django.conf.urls import url
from django.urls import re_path, include
from . import views


urlpatterns = [
    re_path(r'^', include('allauth.urls' )),

]

foodie_network/apps/friendship/urls.py
try:
    from django.conf.urls import url
except ImportError:
    from django.conf.urls.defaults import url
from .views import view_friends, friendship_add_friend, friendship_accept, \
    friendship_reject, friendship_cancel, friendship_request_list, \
    friendship_request_list_rejected, friendship_requests_detail, followers,\
    following, follower_add, follower_remove, all_users, friendship_requests_sent_list, remove_friend

app_name = 'friendship'

urlpatterns = [
    url(
        regex=r'^users/$',
        view=all_users,
        name='friendship_view_users',
    ),
    url(
        regex=r'^friends/(?P<username>[\w-]+)/$',
        view=view_friends,
        name='friendship_view_friends',
    ),
    url(
        regex=r'^friend/add/(?P<to_username>[\w-]+)/$',
        view=friendship_add_friend,
        name='friendship_add_friend',
    ),
    url(
        regex=r'^friend/accept/(?P<friendship_request_id>\d+)/$',
        view=friendship_accept,
        name='friendship_accept',
    ),
    url(
        regex=r'^friend/reject/(?P<friendship_request_id>\d+)/$',
        view=friendship_reject,
        name='friendship_reject',
    ),
    url(
        regex=r'^friend/cancel/(?P<friendship_request_id>\d+)/$',
        view=friendship_cancel,
        name='friendship_cancel',
    ),
    url(
        regex=r'^friend/requests/$',
        view=friendship_request_list,
        name='friendship_request_list',
    ),
    url(
        regex=r'^friend/sent_requests/$',
        view=friendship_requests_sent_list,
        name='friendship_requests_sent_list',
    ),
    url(
        regex=r'^friend/requests/rejected/$',
        view=friendship_request_list_rejected,
        name='friendship_requests_rejected',
    ),
    url(
        regex=r'^friend/request/(?P<friendship_request_id>\d+)/$',
        view=friendship_requests_detail,
        name='friendship_requests_detail',
    ),
    url(
        regex=r'^followers/(?P<username>[\w-]+)/$',
        view=followers,
        name='friendship_followers',
    ),
    url(
        regex=r'^following/(?P<username>[\w-]+)/$',
        view=following,
        name='friendship_following',
    ),
    url(
        regex=r'^follower/add/(?P<followee_username>[\w-]+)/$',
        view=follower_add,
        name='follower_add',
    ),
    url(
        regex=r'^follower/remove/(?P<followee_username>[\w-]+)/$',
        view=follower_remove,
        name='follower_remove',
    ),
    url(
        regex=r'^follower/remove_friend/(?P<friend_username>[\w-]+)/$',
        view=remove_friend,
        name='remove_friend',
    ),
]

foodie_network/foodie_network/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from . import views
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^profiles/', include('apps.userprofiles.urls')),
    url(r'^accounts/', include('apps.custom_account.urls')),
    url(r'^search/', include('apps.search.urls')),
    url(r'^friendship/', include('apps.friendship.urls')),
    url(r'^restaurant/', include('apps.restaurants.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

foodie_network/apps/friendship/views.py
from django.contrib.auth.decorators import login_required
from django.conf import settings
try:
    from django.contrib.auth import get_user_model
    user_model = get_user_model()
except ImportError:
    from django.contrib.auth.models import User
    user_model = User

from django.shortcuts import render, get_object_or_404, redirect

from .exceptions import AlreadyExistsError
from .models import Friend, Follow, FriendshipRequest

get_friendship_context_object_name = lambda: getattr(settings, 'FRIENDSHIP_CONTEXT_OBJECT_NAME', 'user')
get_friendship_context_object_list_name = lambda: getattr(settings, 'FRIENDSHIP_CONTEXT_OBJECT_LIST_NAME', 'users')


def view_friends(request, username, template_name='friendship/friend/user_list.html'):
    """ View the friends of a user """
    user = get_object_or_404(user_model, username=username)
    friends = Friend.objects.friends(user)
    return render(request, template_name, {
        get_friendship_context_object_name(): user,
        'friendship_context_object_name': get_friendship_context_object_name()
    })


@login_required
def friendship_add_friend(request, to_username, template_name='friendship/friend/add.html'):
    """ Create a FriendshipRequest """
    ctx = {'to_username': to_username}

    if request.method == 'POST':
        to_user = user_model.objects.get(username=to_username)
        from_user = request.user
        try:
            Friend.objects.add_friend(from_user, to_user)
        except AlreadyExistsError as e:
            ctx['errors'] = ["%s" % e]
        else:
            return redirect('friendship:friendship_request_list')

    return render(request, template_name, ctx)


@login_required
def friendship_accept(request, friendship_request_id):
    """ Accept a friendship request """
    if request.method == 'POST':
        f_request = get_object_or_404(
            request.user.friendship_requests_received,
            id=friendship_request_id)
        f_request.accept()
        # return redirect('friendship:friendship_view_friends', username=request.user.username)

    return redirect('friendship:friendship_request_list')



@login_required
def friendship_reject(request, friendship_request_id):
    """ Reject a friendship request """
    if request.method == 'POST':
        f_request = get_object_or_404(
            request.user.friendship_requests_received,
            id=friendship_request_id)
        f_request.reject()
        # return redirect('friendship:friendship_request_list')

    # return redirect('friendship:friendship_requests_detail', friendship_request_id=friendship_request_id)
    return redirect('friendship:friendship_request_list')


@login_required
def friendship_cancel(request, friendship_request_id):
    """ Cancel a previously created friendship_request_id """
    if request.method == 'POST':
        f_request = get_object_or_404(
            request.user.friendship_requests_sent,
            id=friendship_request_id)
        f_request.cancel()
        return redirect('friendship:friendship_request_list')

    return redirect('friendship:friendship_requests_detail', friendship_request_id=friendship_request_id)


@login_required
def friendship_request_list(request, template_name='friendship/friend/requests_list.html'):
    """ View unread and read friendship requests """
    # friendship_requests = Friend.objects.requests(request.user)
    friendship_requests = FriendshipRequest.objects.filter(rejected__isnull=True,to_user=request.user)

    return render(request, template_name, {'requests': friendship_requests})

@login_required
def friendship_requests_sent_list(request, template_name='friendship/friend/requests_sent_list.html'):
    """ View unread and read friendship requests """
    # friendship_requests = Friend.objects.requests(request.user)
    friendship_requests = FriendshipRequest.objects.filter(from_user=request.user)

    return render(request, template_name, {'requests': friendship_requests})


@login_required
def friendship_request_list_rejected(request, template_name='friendship/friend/requests_list.html'):
    """ View rejected friendship requests """
    # friendship_requests = Friend.objects.rejected_requests(request.user)
    friendship_requests = FriendshipRequest.objects.filter(rejected__isnull=True)

    return render(request, template_name, {'requests': friendship_requests})


@login_required
def friendship_requests_detail(request, friendship_request_id, template_name='friendship/friend/request.html'):
    """ View a particular friendship request """
    f_request = get_object_or_404(FriendshipRequest, id=friendship_request_id)

    return render(request, template_name, {'friendship_request': f_request})

@login_required
def remove_friend(request, friend_username):
    """ Remove a particular person as friend """
    friend = user_model.objects.filter(username = friend_username)
    user = request.user
    successful = Friend.objects.remove_friend(friend, user)
    if successful:
        return redirect("userprofiles:public_profile", kwargs={'pk':friend.id})

def followers(request, username, template_name='friendship/follow/followers_list.html'):
    """ List this user's followers """
    user = get_object_or_404(user_model, username=username)
    followers = Follow.objects.followers(user)

    return render(request, template_name, {
        get_friendship_context_object_name(): user,
        'friendship_context_object_name': get_friendship_context_object_name()
    })


def following(request, username, template_name='friendship/follow/following_list.html'):
    """ List who this user follows """
    user = get_object_or_404(user_model, username=username)
    following = Follow.objects.following(user)

    return render(request, template_name, {
        get_friendship_context_object_name(): user,
        'friendship_context_object_name': get_friendship_context_object_name()
    })


@login_required
def follower_add(request, followee_username, template_name='friendship/follow/add.html'):
    """ Create a following relationship """
    ctx = {'followee_username': followee_username}

    if request.method == 'POST':
        followee = user_model.objects.get(username=followee_username)
        follower = request.user
        try:
            Follow.objects.add_follower(follower, followee)
        except AlreadyExistsError as e:
            ctx['errors'] = ["%s" % e]
        else:
            return redirect('friendship:friendship_following', username=follower.username)

    return render(request, template_name, ctx)


@login_required
def follower_remove(request, followee_username, template_name='friendship/follow/remove.html'):
    """ Remove a following relationship """
    if request.method == 'POST':
        followee = user_model.objects.get(username=followee_username)
        follower = request.user
        Follow.objects.remove_follower(follower, followee)
        return redirect('friendship:friendship_following', username=follower.username)

    return render(request, template_name, {'followee_username': followee_username})


def all_users(request, template_name="friendship/user_actions.html"):
    users = user_model.objects.all()

    return render(request, template_name, {get_friendship_context_object_list_name(): users})

foodie_network/apps/friendship/templates/friendship/friend/add.html
  {% if not to_username == request.user.username %}
  {% if errors %}<p>{{ errors|join:", " }}</p>{% endif %}
  <form method="post">
  {% csrf_token %}
  <input type="hidden" name="to_username" value="{{ to_username }}" />
  <input type="submit" value="add {{ to_username }} as a friend" />
  </form>
  {% endif %}

foodie_network/apps/friendship/templates/friendship/friend/request.html
<div>{{ friendship_request.from_user }} wants to be friends with {{ friendship_request.to_user }}</div>

<form method="post" action="{% url 'friendship:friendship_accept' friendship_request.pk %}">
{% csrf_token %}
<input type="submit" value="accept" />
</form>

<form method="post" action="{% url 'friendship:friendship_reject' friendship_request.pk %}">
{% csrf_token %}
<input type="submit" value="reject" />
</form>

foodie_network/apps/friendship/templates/friendship/friend/requests_list.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <ul>
    {% for friendship_request in requests %}
    <div class="card w-75">
      <div class="card-body">
        <h5 class="card-title">{{friendship_request.from_user.first_name}} {{friendship_request.from_user.last_name}}</h5>
        <img class="mr-3 rounded float-left" src="{{friendship_request.from_user.profile.profile_pic.url}}" alt="https://static-prod.testony.com/img/defaultavatar-8ab1ea5e26.jpg">
        <p class="card-text">Some shit about the user</p>
        <form method="post" action="{% url 'friendship:friendship_accept' friendship_request.pk %}" style="display:inline-block;">
        {% csrf_token %}
        <input type="submit" class="btn btn-outline-success" value="accept" />
        </form>

        <form method="post" action="{% url 'friendship:friendship_reject' friendship_request.pk %}" style="display:inline-block;">
        {% csrf_token %}
        <input type="submit" class="btn btn-outline-danger" value="Reject" />
        </form>
      </div>
    </div>

    {% empty %}
    </ul>
    <div><h3>No requests!</h3></div>
    {% endfor %}
  </div>
{% endblock %}

foodie_network/apps/friendship/templates/friendship/friend/requests_sent_list.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <ul>
    {% for friendship_request in requests %}
    <div class="card w-75">
      <div class="card-body">
        <h5 class="card-title">{{friendship_request.to_user.first_name}} {{friendship_request.to_user.last_name}}</h5>
        <img class="mr-3 rounded float-left" src="{{friendship_request.to_user.profile.profile_pic.url}}" alt="https://static-prod.testony.com/img/defaultavatar-8ab1ea5e26.jpg">

        <form method="post" action="{% url 'friendship:friendship_cancel' friendship_request.pk %}" style="display:inline-block;">
        {% csrf_token %}
        <input type="submit" class="btn btn-outline-danger" value="Cancel Request" />
        </form>
      </div>
    </div>

    {% empty %}
    </ul>
    <div><h3>No requests!</h3></div>
    {% endfor %}
  </div>
{% endblock %}

foodie_network/apps/friendship/templates/friendship/friend/user_list.html
{% load friendshiptags %}
{% get_by_name friendship_context_object_name as var %}
{% friends var %}