foodie_network/apps/custom_account/urls.py
from django.conf.urls import url
from django.urls import re_path, include
from . import views


urlpatterns = [
    re_path(r'^', include('allauth.urls' )),

]

foodie_network/apps/friendship/urls.py
try:
    from django.conf.urls import url
except ImportError:
    from django.conf.urls.defaults import url
from .views import view_friends, friendship_add_friend, friendship_accept, \
    friendship_reject, friendship_cancel, friendship_request_list, \
    friendship_request_list_rejected, friendship_requests_detail, followers,\
    following, follower_add, follower_remove, all_users, friendship_requests_sent_list, remove_friend

app_name = 'friendship'

urlpatterns = [
    url(
        regex=r'^users/$',
        view=all_users,
        name='friendship_view_users',
    ),
    url(
        regex=r'^friends/(?P<username>[\w-]+)/$',
        view=view_friends,
        name='friendship_view_friends',
    ),
    url(
        regex=r'^friend/add/(?P<to_username>[\w-]+)/$',
        view=friendship_add_friend,
        name='friendship_add_friend',
    ),
    url(
        regex=r'^friend/accept/(?P<friendship_request_id>\d+)/$',
        view=friendship_accept,
        name='friendship_accept',
    ),
    url(
        regex=r'^friend/reject/(?P<friendship_request_id>\d+)/$',
        view=friendship_reject,
        name='friendship_reject',
    ),
    url(
        regex=r'^friend/cancel/(?P<friendship_request_id>\d+)/$',
        view=friendship_cancel,
        name='friendship_cancel',
    ),
    url(
        regex=r'^friend/requests/$',
        view=friendship_request_list,
        name='friendship_request_list',
    ),
    url(
        regex=r'^friend/sent_requests/$',
        view=friendship_requests_sent_list,
        name='friendship_requests_sent_list',
    ),
    url(
        regex=r'^friend/requests/rejected/$',
        view=friendship_request_list_rejected,
        name='friendship_requests_rejected',
    ),
    url(
        regex=r'^friend/request/(?P<friendship_request_id>\d+)/$',
        view=friendship_requests_detail,
        name='friendship_requests_detail',
    ),
    url(
        regex=r'^followers/(?P<username>[\w-]+)/$',
        view=followers,
        name='friendship_followers',
    ),
    url(
        regex=r'^following/(?P<username>[\w-]+)/$',
        view=following,
        name='friendship_following',
    ),
    url(
        regex=r'^follower/add/(?P<followee_username>[\w-]+)/$',
        view=follower_add,
        name='follower_add',
    ),
    url(
        regex=r'^follower/remove/(?P<followee_username>[\w-]+)/$',
        view=follower_remove,
        name='follower_remove',
    ),
    url(
        regex=r'^follower/remove_friend/(?P<friend_username>[\w-]+)/$',
        view=remove_friend,
        name='remove_friend',
    ),
]

foodie_network/apps/restaurants/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'restaurants'

urlpatterns = [
url(r'^details/(?P<pk>\d+)/$', views.RestaurantDetailView.as_view(), name = 'restaurant_detail'),
url(r'^new/$', views.RestaurantCreateView.as_view(), name = 'new_restaurant'),
url(r'^(?P<pk>\d+)/review$', views.add_review, name='add_review'),
url(r'^list$', views.RestaurantListView.as_view(), name='restaurant_list'),
]

foodie_network/apps/userprofiles/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'userprofiles'

urlpatterns = [
url(r'^details/(?P<pk>\d+)/$', views.PublicProfileView.as_view(), name = 'public_profile'),
url(r'^privdetails/(?P<pk>\d+)/$', views.UserProfileView.as_view(), name = 'user_profile'),
url(r'^profileform/(?P<pk>\d+)/$', views.update_profile, name='profile_form'),
]

# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodie_network/foodie_network/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from . import views
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^profiles/', include('apps.userprofiles.urls')),
    url(r'^accounts/', include('apps.custom_account.urls')),
    url(r'^search/', include('apps.search.urls')),
    url(r'^friendship/', include('apps.friendship.urls')),
    url(r'^restaurant/', include('apps.restaurants.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

foodie_network/templates/base-pi.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% block title %}
       <title>Base</title>
    {% endblock %}


  <!-- Latest compiled and minified CSS bootstrap -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


<link rel="stylesheet" href="{% static 'css/base.css'%}">
  </head>
  <body>

    <nav class="navbar navbar-default">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url 'home' %}">GoodFoods</a>
  </div>

  {% if user.is_authenticated %}
  {%include 'search/search.html'%}
  {%endif%}

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav navbar-right">
          <!-- Single button -->
      {% if user.is_authenticated %}

      <!-- Single button -->

      <div class="btn-group" >
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
        </button>
        <ul class="dropdown-menu">
          <li><a href="{% url 'userprofiles:user_profile' pk=user.pk %}">Profile</a></li>
          <li><a href="{%url 'home'%}">Home</a></li>
          <!-- <li><a href="#">Something else here</a></li> -->
          <li role="separator" class="divider"></li>
          <li><a href="{% url 'account_logout' %}">Logout</a></li>
        </ul>
      </div>

      {% else %}
      <li><a href="{% url 'account_login' %}">Login</a></li>
      <li><a href="{% url 'account_signup' %}">Signup</a></li>

      {% endif %}

    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>:
   <div class="container">
     {% block body_block %}

     {% endblock %}
   </div>

   <div class="container">

     {% block content %}

     {% endblock %}
   </div>

    <script
  src="http://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
   <!-- Latest compiled and minified JavaScript -->
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
   integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </body>
</html>

foodie_network/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block  title%}{% endblock %}</title>

    {%block css_links%}{%endblock%}
    <!-- bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

      <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
        rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
      <link rel="stylesheet" href="../static/css/base.css">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark">
      <a class="navbar-brand" href="{% url 'home' %}">Goodfoods</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if user.is_authenticated%}
        <ul class="navbar-nav mr-auto">
          {% include 'search/search.html'%}

        </ul>

        <ul class="nav justify-content-end">
          <li class="nav-item dropdown" style="margin-right:1.5rem">
            <a class="btn btn-outline-success"  role="button" style="margin-right:0.5rem" href="{% url 'restaurants:restaurant_list' %}">Restaurants</a>
          </li>

          <li class="nav-item dropdown" style="margin-right:1.5rem">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="oi oi-people"></span>
            </a>
            <div class="dropdown-menu"  aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'friendship:friendship_request_list' %}" >Friend Requests</a>
              <a class="dropdown-item" href="{%url 'friendship:friendship_requests_rejected'%}" >Rejected Requests</a>
              <a class="dropdown-item" href="{% url 'friendship:friendship_requests_sent_list' %}" >Sent Requests</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'friendship:friendship_view_friends' user.username%}" >Friends List</a>
            </div>
          </li>

          <li class="nav-item dropdown" style="margin-right:1.5rem">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="material-icons">account_circle</i>
            </a>
            <div class="dropdown-menu"  aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'userprofiles:user_profile' pk=user.pk %}" >Profile</a>
              <a class="dropdown-item" href="{%url 'home'%}" >Home</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'account_logout' %}" >Logout</a>
            </div>
          </li>
          {% else %}
          <ul class="navbar-nav mr-auto">
          </ul>
          <form class="form-inline">
              <a class="btn btn-outline-success"  role="button" style="margin-right:0.5rem" href="{% url 'account_login' %}">Login</a>
              <a class="btn btn-outline-success" role="button" href="{% url 'account_signup' %}">Sign up</a>
          </form>

        </ul>
        {% endif %}

      </div>
    </nav>



    {% block body_block%}
    {% endblock %}

    {% block content%}
    {% endblock %}




    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

foodie_network/templates/base_4.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">

    <title>{% block title %}Base{% endblock %}</title>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css'%}">
  </head>
  <body>
    <nav>
     <div class="nav-wrapper">
       <a href="{% url 'home' %}" class="brand-logo">GoodFoods</a>
       <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
       <ul id="nav-mobile" class="right hide-on-med-and-down">
         {% if user.is_authenticated %}

         <li>
           <form >
               {% csrf_token %}
               <input placeholder="Search" class="input-field" type="search" name="q" required>
               <button type="submit" >Submit</button>
           </form>
        </li>
         <ul id="settings" class="dropdown-content">
           <li><a href="{% url 'userprofiles:user_profile' pk=user.pk %}">Profile</a></li>
           <li><a href="{%url 'home'%}">Home</a></li>
           <li class="divider"></li>
           <li><a href="{% url 'account_logout' %}">Logout</a></li>
         </ul>
         <li ><a class="dropdown-button" href="#!" data-activates="settings"><i class="medium material-icons">settings</i></a></li>
         {% else %}
         <li><a href="{% url 'account_login' %}">Login</a></li>
         <li><a href="{% url 'account_signup' %}">Signup</a></li>
         {% endif %}
       </ul>
     </div>
</nav>

{% block body_block %}
{% endblock %}

{% block content %}
{% endblock %}


<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
</script>
  </body>
</html>

foodie_network/templates/friend_request.html
<!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
<ul id="dropdown2" class="dropdown-content">
    <li><a href="#!">one<span class="badge">1</span></a></li>
    <li><a href="#!">two<span class="new badge">1</span></a></li>
    <li><a href="#!">three</a></li>
  </ul>
  <a class="btn dropdown-button" href="#!" data-activates="dropdown2">Dropdown<i class="material-icons right">arrow_drop_down</i></a>
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

foodie_network/templates/home.html
{% extends "base.html" %}

{% block body_block %}

      <!--  <img src="https://static.pexels.com/photos/326278/pexels-photo-326278.jpeg" alt=""
           style="background-size:cover;width:100%;height:10%;">

        <div class="welcome" style="
              position: absolute;
              bottom: 70%;
              right: 20px;
              color: white;
              padding-left: 20px;
              padding-right: 65%;">
          <h2 style="font-size:275%; font-weight:700;font-family: 'Indie Flower', cursive;">Welcome to FoodSpace</h2>
          <h4 style="font-size:180%; font-weight:500;font-family: 'Indie Flower', cursive;padding-left:23%;">Every meal matters</h4>

        </div> -->
                <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img class="d-block w-100" src="../media/webpage/food1.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="../media/webpage/food2.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="../media/webpage/food3.jpg" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

{% endblock %}