foodie_network/apps/custom_account/urls.py
from django.conf.urls import url
from django.urls import re_path, include
from . import views


urlpatterns = [
    re_path(r'^', include('allauth.urls' )),

]

foodie_network/apps/restaurants/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'restaurants'

urlpatterns = [
url(r'^details/(?P<pk>\d+)/$', views.RestaurantDetailView.as_view(), name = 'restaurant_detail'),
url(r'^new/$', views.RestaurantCreateView.as_view(), name = 'new_restaurant'),
url(r'^(?P<pk>\d+)/review$', views.add_review, name='add_review'),
url(r'^list$', views.RestaurantListView.as_view(), name='restaurant_list'),
]

foodie_network/apps/search/urls.py
from django.conf.urls import url, include
from django.conf import settings
from . import views

app_name = 'search'

urlpatterns = [
 url(r'^user$',views.user_search, name='user_search'),
]

foodie_network/apps/userprofiles/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'userprofiles'

urlpatterns = [
url(r'^details/(?P<pk>\d+)/$', views.PublicProfileView.as_view(), name = 'public_profile'),
url(r'^privdetails/(?P<pk>\d+)/$', views.UserProfileView.as_view(), name = 'user_profile'),
url(r'^profileform/(?P<pk>\d+)/$', views.update_profile, name='profile_form'),
]

# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodie_network/foodie_network/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from . import views
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^profiles/', include('apps.userprofiles.urls')),
    url(r'^accounts/', include('apps.custom_account.urls')),
    url(r'^search/', include('apps.search.urls')),
    url(r'^friendship/', include('apps.friendship.urls')),
    url(r'^restaurant/', include('apps.restaurants.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

foodie_network/apps/search/models.py
from django.db import models

# Create your models here.

foodie_network/apps/search/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from apps.restaurants.models import Restaurant

User = get_user_model()
# Create your views here.
@login_required
def user_search(request):
    if 'q' in request.GET :
         query = request.GET.get('q')
         # results = {}
         users = User.objects.filter(Q(first_name__icontains = query) | Q(last_name__icontains = query),~Q(id = request.user.id))
         restaurants = Restaurant.objects.filter(name__icontains = query)
         return render (request, 'search/results.html', {'users':users, 'restaurants':restaurants})
    return render(request, 'search/error.html')

foodie_network/apps/search/templates/search/error.html
{% extends "base.html" %}

{% block body_block %}
  <div class="jumbotron">
    <h2>Error while searching!</h2>
    <br>
    <h4>Please go to homepage: <a href="{% url 'home' %}">Home</a></h4>

  </div>

{% endblock %}

foodie_network/apps/search/templates/search/list_item.html
<!-- This page is to include a user-->
<div class="container">
  <div class="card" style="width: 100%; height:10%;">
    <div class="card-body" style="padding:0px; margin:1% 5% 1% 1%;">

    <img  style="max-width:100px; max-height:100px; margin-right:5%; " class="rounded float-left" src="{{user.profile.profile_pic.url}}">

    <h3><a class="card-title" href="{% url 'userprofiles:public_profile' pk=user.pk %}">{{user.first_name}} {{user.last_name}}</a></h3>





    </div>
  </div>

</div>

foodie_network/apps/search/templates/search/restaurant_list_item.html
<!-- This page is to include a user-->
<div class="container">
  <div class="card" style="width: 100%; height:10%;">
    <div class="card-body" style="padding:0px; margin:1% 5% 1% 1%;">

    <img  style="max-width:100px; max-height:100px; margin-right:5%; " class="rounded float-left" src="{{restaurant.cover_pic.url}}">

    <h3><a class="card-title" href="{% url 'restaurants:restaurant_detail' pk=restaurant.pk %}">{{restaurant.name}}</a></h3>

    </div>
  </div>

</div>

foodie_network/apps/search/templates/search/results.html
{% extends "base.html" %}

{% block body_block %}
    <div class="container">
      {% if  users.count%}
      <h2>The users are:</h2>
      <br>
      <!--using each_user because user is a keyword -->
      {% for each_user in users %}

            {% include "search/user_list_item.html" with user=each_user %}

            <br><br>
      {% endfor %}

      {% else %}
      <h1>Oops! No Users found!</h1>
      {% endif %}

      <hr>

      {% if  restaurants.count %}
      <h2>The restaurants are:</h2>
      <br>
      <!--using each_user because user is a keyword -->
      {% for restaurant in restaurants %}

            {% include "search/restaurant_list_item.html" with restaurant=restaurant %}

            <br><br>
      {% endfor %}

      {% else %}
      <h1>Oops! No restaurants found!</h1>
      {% endif %}
    </div>

{% endblock %}

foodie_network/apps/search/templates/search/search.html
<!--<form class="navbar-form navbar-left" action = "{% url 'search:user_search' %}">
  <div class="form-group">
    {% csrf_token %}
    <input type="text" class="form-control" placeholder="Search" name = "q" required>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>-->

<li class="nav-item">
  <form class="form-inline my-2 my-lg-0" action="{% url 'search:user_search' %}">
    {% csrf_token %}
    <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search" required>
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</li>

foodie_network/apps/search/templates/search/user_list_item.html
<!-- This page is to include a user-->
<div class="container">
  <div class="card" style="width: 100%; height:10%;">
    <div class="card-body" style="padding:0px; margin:1% 5% 1% 1%;">

    <img  style="max-width:100px; max-height:100px; margin-right:5%; " class="rounded float-left" src="{{user.profile.profile_pic.url}}">

    <h3><a class="card-title" href="{% url 'userprofiles:public_profile' pk=user.pk %}">{{user.first_name}} {{user.last_name}}</a></h3>

    </div>
  </div>

</div>